export const BATCH_ORDERS_V4_5 = [
  {
    "id": "batch-b1",
    "refContrat": "contrat 13/2023",
    "refOds": "univ annaba N° 13",
    "client": "Université Annaba Faculté des sciences de la terre",
    "division": "Direction Laboratoire",
    "objet": "Acquisition d'équip",
    "montantTtc": 2499000,
    "status": "En attente de paiement",
    "paymentStatus": "Aucun",
    "montantVerse": 0,
    "dateLivraison": "2026-03-01",
    "createdAt": "2026-04-26T10:00:00Z"
  },
  {
    "id": "batch-b2",
    "refContrat": "CRAPC N°08",
    "refOds": "08/CRAPC/2023",
    "client": "CRAPC",
    "division": "Direction Laboratoire",
    "objet": "acquisition installation",
    "montantTtc": 1414951.60,
    "status": "En attente de paiement",
    "paymentStatus": "Aucun",
    "montantVerse": 0,
    "createdAt": "2026-04-26T10:00:01Z"
  },
  {
    "id": "batch-b3",
    "refContrat": "SAIDAL EQUIPEMENT",
    "refOds": "12/2023",
    "client": "SAIDAL",
    "division": "Direction Laboratoire",
    "objet": "acquisition installation",
    "montantTtc": 5196016,
    "status": "En attente de paiement",
    "paymentStatus": "Aucun",
    "montantVerse": 0,
    "createdAt": "2026-04-26T10:00:02Z"
  },
  {
    "id": "batch-b4",
    "refContrat": "Marché N°234/2024",
    "refOds": "Marché N°234/2024",
    "client": "INCC",
    "division": "Direction Analytique",
    "objet": "acquisition installation",
    "montantTtc": 193772595.96,
    "status": "En attente de paiement",
    "paymentStatus": "Aucun",
    "montantVerse": 0,
    "createdAt": "2026-04-26T10:00:03Z"
  },
  {
    "id": "batch-b5",
    "refContrat": "Contrat N°001/2024",
    "refOds": "SAIDAL 01/2024",
    "client": "SAIDAL CHERCHEL",
    "division": "Direction Laboratoire",
    "objet": "acquisition installation",
    "montantTtc": 6199900.00,
    "status": "En attente de paiement",
    "paymentStatus": "Aucun",
    "montantVerse": 0,
    "createdAt": "2026-04-26T10:00:04Z"
  },
  {
    "id": "batch-b6",
    "refContrat": "Contrat N°002/2024",
    "refOds": "saidal cherchel 02/",
    "client": "SAIDAL CHERCHEL",
    "division": "Direction Laboratoire",
    "objet": "acquisition installation",
    "montantTtc": 7304220,
    "status": "En attente de paiement",
    "paymentStatus": "Aucun",
    "montantVerse": 0,
    "createdAt": "2026-04-26T10:00:05Z"
  },
  {
    "id": "batch-b7",
    "refContrat": "Contrat N°DS/ELH/DAA/0",
    "refOds": "Contrat N°DS/ELH/D",
    "client": "SAIDAL EL HARRACH",
    "division": "Direction Laboratoire",
    "objet": "acquisition installation",
    "montantTtc": 21171290,
    "status": "En attente de paiement",
    "paymentStatus": "Aucun",
    "montantVerse": 0,
    "createdAt": "2026-04-26T10:00:06Z"
  },
  {
    "id": "batch-b8",
    "refContrat": "Contrat N°04/DAC/MED/",
    "refOds": "Contrat N°04/DAC/M",
    "client": "SAIDAL MEDEA",
    "division": "Direction Laboratoire",
    "objet": "acquisition installation",
    "montantTtc": 6544312.41,
    "status": "En attente de paiement",
    "paymentStatus": "Aucun",
    "montantVerse": 0,
    "createdAt": "2026-04-26T10:00:07Z"
  },
  {
    "id": "batch-b9",
    "refContrat": "Marché N°01/CACQE/202",
    "refOds": "Marché N°01/CACC",
    "client": "CACQE",
    "division": "Direction Laboratoire",
    "objet": "Installation et mise",
    "montantTtc": 85888766.15,
    "status": "En attente de paiement",
    "paymentStatus": "Aucun",
    "montantVerse": 0,
    "createdAt": "2026-04-26T10:00:08Z"
  },
  {
    "id": "batch-b10",
    "refContrat": "002/25",
    "refOds": "CONTRAT 002/25",
    "client": "saidal cherchell",
    "division": "Direction Laboratoire",
    "objet": "Installation et mise",
    "montantTtc": 2375240,
    "status": "En attente de paiement",
    "paymentStatus": "Aucun",
    "montantVerse": 0,
    "createdAt": "2026-04-26T10:00:09Z"
  },
  {
    "id": "batch-b11",
    "refContrat": "003/25",
    "refOds": "003/25",
    "client": "saidal cherchell",
    "division": "Direction Analytique",
    "objet": "Installation et mise",
    "montantTtc": 9520000,
    "status": "En attente de paiement",
    "paymentStatus": "Aucun",
    "montantVerse": 0,
    "createdAt": "2026-04-26T10:00:10Z"
  },
  {
    "id": "batch-b12",
    "refContrat": "Marché N°03/CACQE/202",
    "refOds": "Marché N°03/CACC",
    "client": "CACQE",
    "division": "Direction Analytique",
    "objet": "Installation et mise",
    "montantTtc": 203048323,
    "status": "En attente de paiement",
    "paymentStatus": "Aucun",
    "montantVerse": 0,
    "createdAt": "2026-04-26T10:00:11Z"
  },
  {
    "id": "batch-b13",
    "refContrat": "001/2025",
    "refOds": "001/2025",
    "client": "saidal dar el beida",
    "division": "Direction Analytique",
    "objet": "Installation et mise",
    "montantTtc": 3870000,
    "status": "En attente de paiement",
    "paymentStatus": "Aucun",
    "montantVerse": 0,
    "createdAt": "2026-04-26T10:00:12Z"
  },
  {
    "id": "batch-b14",
    "refContrat": "CONTRAT N 09/2025",
    "refOds": "SLAAL 09/2025",
    "client": "SLAAL",
    "division": "Direction Laboratoire",
    "objet": "Installation et mise",
    "montantTtc": 12041372,
    "status": "En attente de paiement",
    "paymentStatus": "Aucun",
    "montantVerse": 0,
    "createdAt": "2026-04-26T10:00:13Z"
  },
  {
    "id": "batch-b15",
    "refContrat": "INCC 321/005",
    "refOds": "321/005",
    "client": "INCC",
    "division": "Direction Laboratoire",
    "objet": "Installation et mise",
    "montantTtc": 58878773.53,
    "status": "En attente de paiement",
    "paymentStatus": "Aucun",
    "montantVerse": 0,
    "createdAt": "2026-04-26T10:00:14Z"
  },
  {
    "id": "batch-b16",
    "refContrat": "05/CACQE/2024",
    "refOds": "05/CACQE/2024",
    "client": "CACQE",
    "division": "Direction Analytique",
    "objet": "Installation et mise",
    "montantTtc": 117045663,
    "status": "En attente de paiement",
    "paymentStatus": "Aucun",
    "montantVerse": 0,
    "createdAt": "2026-04-26T10:00:15Z"
  },
  {
    "id": "batch-b17",
    "refContrat": "N° F1107 / 24 DCM",
    "refOds": "DCM N° F1107 / 24",
    "client": "Direction Centrale du Matériel DCM",
    "division": "Direction Laboratoire",
    "objet": "Installation et mise",
    "montantTtc": 3375174.00,
    "status": "En attente de paiement",
    "paymentStatus": "Aucun",
    "montantVerse": 0,
    "createdAt": "2026-04-26T10:00:16Z"
  },
  {
    "id": "batch-b18",
    "refContrat": "DSP ORAN /HMID 52/24",
    "refOds": "DSP ORAN 52/24",
    "client": "DSP ORAN /HMID 52/24",
    "division": "Direction Laboratoire",
    "objet": "Installation et mise",
    "montantTtc": 91639772.00,
    "status": "En attente de paiement",
    "paymentStatus": "Aucun",
    "montantVerse": 0,
    "createdAt": "2026-04-26T10:00:17Z"
  },
  {
    "id": "batch-b19",
    "refContrat": "CRBT 04/2025",
    "refOds": "CRBT 04/2025",
    "client": "CRBT",
    "division": "Direction Laboratoire",
    "objet": "Acqui, inst, mise",
    "montantTtc": 461500.00,
    "status": "En attente de paiement",
    "paymentStatus": "Aucun",
    "montantVerse": 0,
    "createdAt": "2026-04-26T10:00:18Z"
  },
  {
    "id": "batch-b20",
    "refContrat": "contrat 13 & 14",
    "refOds": "SAIDAL ELU 13/2025",
    "client": "saidal ELU",
    "division": "Direction Analytique",
    "objet": "fournitures et mise",
    "montantTtc": 6511000,
    "status": "En attente de paiement",
    "paymentStatus": "Aucun",
    "montantVerse": 0,
    "createdAt": "2026-04-26T10:00:19Z"
  },
  {
    "id": "batch-b21",
    "refContrat": "Univ SPTIF 13/25",
    "refOds": "Univ SPTIF 13/25",
    "client": "Univ SPTIF 01/2025",
    "division": "Direction Laboratoire",
    "objet": "Acquisition d'équip",
    "montantTtc": 899999.43,
    "status": "En attente de paiement",
    "paymentStatus": "Aucun",
    "montantVerse": 0,
    "createdAt": "2026-04-26T10:00:20Z"
  },
  {
    "id": "batch-b22",
    "refContrat": "UKAPC",
    "refOds": "UKAPC",
    "client": "UKAPC",
    "division": "Direction Laboratoire",
    "objet": "Installation et mise",
    "montantTtc": 0,
    "status": "En attente de paiement",
    "paymentStatus": "Aucun",
    "montantVerse": 0,
    "createdAt": "2026-04-26T10:00:21Z"
  },
  {
    "id": "batch-b23",
    "refContrat": "RAFTIN ARF7W N°INV 7",
    "refOds": "RAFTIN ARF7W N°",
    "client": "RAFTINNPRF ARF7W",
    "division": "Direction Analytique",
    "objet": "Fourniture et mise",
    "montantTtc": 15282518.00,
    "status": "En attente de paiement",
    "paymentStatus": "Aucun",
    "montantVerse": 0,
    "createdAt": "2026-04-26T10:00:22Z"
  },
  {
    "id": "batch-b24",
    "refContrat": "Contrat N°09/2024",
    "refOds": "LNP 09/2024",
    "client": "LNP CONSTANTINE",
    "division": "Direction Laboratoire",
    "objet": "Acquisition d'équi",
    "montantTtc": 21704430,
    "status": "En attente de paiement",
    "paymentStatus": "Aucun",
    "montantVerse": 0,
    "createdAt": "2026-04-26T10:00:23Z"
  },
  {
    "id": "batch-b25",
    "refContrat": "BC GTFT 24725",
    "refOds": "BC GTFT 24725",
    "client": "GTTT",
    "division": "Direction Laboratoire",
    "objet": "Chromatographie et",
    "montantTtc": 44220108,
    "status": "En attente de paiement",
    "paymentStatus": "Aucun",
    "montantVerse": 0,
    "createdAt": "2026-04-26T10:00:24Z"
  },
  {
    "id": "batch-b26",
    "refContrat": "AO N°01/FORHMYD/UN 01/2025",
    "refOds": "FORHMYD 01/2025",
    "client": "FORHMYD STEP ADRAR",
    "division": "Direction Laboratoire",
    "objet": "Fourniture et mise",
    "montantTtc": 44345197.87,
    "status": "En attente de paiement",
    "paymentStatus": "Aucun",
    "montantVerse": 0,
    "createdAt": "2026-04-26T10:00:25Z"
  },
  {
    "id": "batch-b27",
    "refContrat": "SFDA N°15/DG/2024",
    "refOds": "SFDA 15/2024",
    "client": "SFDA",
    "division": "Direction Laboratoire",
    "objet": "Acquisition de prod",
    "montantTtc": 6000000,
    "status": "En attente de paiement",
    "paymentStatus": "Aucun",
    "montantVerse": 0,
    "createdAt": "2026-04-26T10:00:26Z"
  },
  {
    "id": "batch-b28",
    "refContrat": "seaal/DAM UN/2025/L 0",
    "refOds": "seaal/DAM UN/202",
    "client": "SEAAL",
    "division": "Direction Laboratoire",
    "objet": "Acquisition d'équip",
    "montantTtc": 4829531.7,
    "status": "En attente de paiement",
    "paymentStatus": "Aucun",
    "montantVerse": 0,
    "createdAt": "2026-04-26T10:00:27Z"
  },
  {
    "id": "batch-b29",
    "refContrat": "15/CRAPC/2024",
    "refOds": "CRAPC N°15",
    "client": "CRAPC",
    "division": "Direction Laboratoire",
    "objet": "Acquisition et inst",
    "montantTtc": 2084683.1,
    "status": "En attente de paiement",
    "paymentStatus": "Aucun",
    "montantVerse": 0,
    "createdAt": "2026-04-26T10:00:28Z"
  },
  {
    "id": "batch-b30",
    "refContrat": "01/CRD/2024",
    "refOds": "saidal 01/CRD/20",
    "client": "SAIDAL",
    "division": "Direction Laboratoire",
    "objet": "ACQUISITION DES U",
    "montantTtc": 1141072466.29,
    "status": "En attente de paiement",
    "paymentStatus": "Aucun",
    "montantVerse": 0,
    "createdAt": "2026-04-26T10:00:29Z"
  },
  {
    "id": "batch-b31",
    "refContrat": "BC 4500057418",
    "refOds": "002/IT/2024",
    "client": "sonatrach skikda CP2K",
    "division": "Direction Laboratoire",
    "objet": "ACQUISITION D'UN",
    "montantTtc": 1880414.8,
    "status": "En attente de paiement",
    "paymentStatus": "Aucun",
    "montantVerse": 0,
    "createdAt": "2026-04-26T10:00:30Z"
  },
  {
    "id": "batch-b32",
    "refContrat": "N°05/25",
    "refOds": "Contrat N° 05/26",
    "client": "saidal dar el beida",
    "division": "Direction Laboratoire",
    "objet": "Acquisition équipe",
    "montantTtc": 5438300,
    "status": "En attente de paiement",
    "paymentStatus": "Aucun",
    "montantVerse": 0,
    "createdAt": "2026-04-26T10:00:31Z"
  },
  {
    "id": "batch-b33",
    "refContrat": "BC ACHAT CABLE",
    "refOds": "CONSULTATION N°",
    "client": "CRTSE",
    "division": "Direction Laboratoire",
    "objet": "ACHAT DES CABLE",
    "montantTtc": 0,
    "status": "En attente de paiement",
    "paymentStatus": "Aucun",
    "montantVerse": 0,
    "createdAt": "2026-04-26T10:00:32Z"
  },
  {
    "id": "batch-b34",
    "refContrat": "11/2025",
    "refOds": "saidal 15",
    "client": "saidal medea",
    "division": "Direction Laboratoire",
    "objet": "fournitures HPLC",
    "montantTtc": 4109041,
    "status": "En attente de paiement",
    "paymentStatus": "Aucun",
    "montantVerse": 0,
    "createdAt": "2026-04-26T10:00:33Z"
  },
  {
    "id": "batch-b35",
    "refContrat": "126/2025",
    "refOds": "126/2025",
    "client": "serpi",
    "division": "Direction Laboratoire",
    "objet": "Acquisition d'un DE",
    "montantTtc": 1511000,
    "status": "En attente de paiement",
    "paymentStatus": "Aucun",
    "montantVerse": 0,
    "createdAt": "2026-04-26T10:00:34Z"
  },
  {
    "id": "batch-b36",
    "refContrat": "contrat n°23/25",
    "refOds": "contrat n°23/25",
    "client": "Météo algerie",
    "division": "Direction Laboratoire",
    "objet": "Acquisition d'une c",
    "montantTtc": 8733410,
    "status": "En attente de paiement",
    "paymentStatus": "Aucun",
    "montantVerse": 0,
    "createdAt": "2026-04-26T10:00:35Z"
  },
  {
    "id": "batch-b37",
    "refContrat": "Contrat N°02/25",
    "refOds": "CRBT N°02/25",
    "client": "CRBT N°02/25",
    "division": "Direction Laboratoire",
    "objet": "Acqui, insta,et mise",
    "montantTtc": 27867182,
    "status": "En attente de paiement",
    "paymentStatus": "Aucun",
    "montantVerse": 0,
    "createdAt": "2026-04-26T10:00:36Z"
  },
  {
    "id": "batch-b38",
    "refContrat": "Convention N°02",
    "refOds": "convention N° 02 U",
    "client": "UNIVERSITE DE TIARET",
    "division": "Direction Laboratoire",
    "objet": "Acquisition d'EQUI",
    "montantTtc": 6152538,
    "status": "En attente de paiement",
    "paymentStatus": "Aucun",
    "montantVerse": 0,
    "createdAt": "2026-04-26T10:00:37Z"
  },
  {
    "id": "batch-b39",
    "refContrat": "BC 127/25 CONTRAT",
    "refOds": "CHU+B150:B150",
    "client": "CHU+B150:B150 BAB ELOUED",
    "division": "Direction Analytique",
    "objet": "CONSOMMABLE DI",
    "montantTtc": 3816359.44,
    "status": "En attente de paiement",
    "paymentStatus": "Aucun",
    "montantVerse": 0,
    "createdAt": "2026-04-26T10:00:38Z"
  },
  {
    "id": "batch-b40",
    "refContrat": "02/2025",
    "refOds": "AO N°82/2025",
    "client": "Hopital militaire",
    "division": "Direction Maintenance",
    "objet": "Réparation et mise",
    "montantTtc": 386750,
    "status": "En attente de paiement",
    "paymentStatus": "Aucun",
    "montantVerse": 0,
    "createdAt": "2026-04-26T10:00:39Z"
  },
  {
    "id": "batch-b41",
    "refContrat": "SAIDAL 063/25",
    "refOds": "SAIDAL 063/25",
    "client": "SAIDAL DEB",
    "division": "Direction Analytique",
    "objet": "Acquisition et inst",
    "montantTtc": 102340000,
    "status": "En attente de paiement",
    "paymentStatus": "Aucun",
    "montantVerse": 0,
    "createdAt": "2026-04-26T10:00:40Z"
  },
  {
    "id": "batch-b42",
    "refContrat": "BC N°. 001885 Du 09/07/",
    "refOds": "BC 001885",
    "client": "ADE AIN SALAH TAMENRASSET",
    "division": "Direction Analytique",
    "objet": "ACQUISITION ET LI",
    "montantTtc": 7163046.73,
    "status": "En attente de paiement",
    "paymentStatus": "Aucun",
    "montantVerse": 0,
    "createdAt": "2026-04-26T10:00:41Z"
  },
  {
    "id": "batch-b43",
    "refContrat": "MARCHE N° 02/2025 - LO",
    "refOds": "MARCHE N° 02/20",
    "client": "CENTRE DE RECHERCHE EN BIOTECHNOLOGIE (C",
    "division": "Direction Analytique",
    "objet": "ACQUISITION, INST",
    "montantTtc": 27867182.00,
    "status": "En attente de paiement",
    "paymentStatus": "Aucun",
    "montantVerse": 0,
    "createdAt": "2026-04-26T10:00:42Z"
  }
];
